# Bowtie indexes
idx_bt1_mm: /hpcnfs/techunits/bioinformatics/refdata/Mus_musculus/UCSC/mm9/Sequence/BowtieIndex/genome
idx_bt1_dm: /hpcnfs/data/DP/dm6/dm6

# MACS2 parameters
macs2:
  gsize: mm
  pvalue: 1e-5
  pvalue_broad: 1e-5
  # -log10 pvalue for peak filtering -corresponds to the 8th column of the narrowPeak file. Default 10-
  filt_peaks_pval: "5"

# json files
samples: samples.txt
CLUSTER_JSON: cluster.json

# Determine the region corresponding to promoters around TSS
promoter:
  # After TSS
  aTSS: 2500
  # Before TSS
  bTSS: 2500

genome:
  # File required by computeGCbias from deeptools
  2bit: /hpcnfs/data/DP/Databases/mm9.2bit
  # Used in computeGCbias to ignore repetitive regions in the calculation
  rep_masker: /hpcnfs/data/DP/Databases/RepeatMasker_noRandom.bed
  # File required by bdg2bigwig from ucsc
  chr_sizes: /hpcnfs/data/DP/Databases/mm9.chrom.sizes
  # https://deeptools.readthedocs.io/en/latest/content/feature/effectiveGenomeSize.html
  # 2304947926 --> mm9
  # 2308125349 --> mm10
  egenome_size: 2304947926

# Bam2bigwig params
read_extension: 200

