# Bowtie indexes
idx_bt1_mm: /hpcnfs/techunits/bioinformatics/db/bowtie/mm9/mm9
idx_bt1_dm: /hpcnfs/data/DP/dm6/dm6

# MACS2 parameters
macs2_g: mm
macs2_pvalue: 1e-5
macs2_pvalue_broad: 1e-5

# json files
samples: samples.txt
CLUSTER_JSON: cluster.json

# Determine the region corresponding to promoters around TSS
promoter:
  # After TSS
  aTSS: 2500
  # Before TSS
  bTSS: 2500

# Other files related to genomes
# File required by computeGCbias from deeptools
2bit: /hpcnfs/data/DP/Databases/mm9.2bit

# Bam2bigwig + GC content config
chr_sizes: /hpcnfs/scratch/DP/sjammula/mm9/mm9.chrom.sizes
read_extension: 200
egenome_size: 2304947926
rep_masker: /hpcnfs/data/DP/Databases/RepeatMasker_noRandom.bed