# path to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.txt

# Parameters for submitting jobs to cluster via qsub
cluster: cluster.yaml

# path to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: units.tsv
input: "/hpcnfs/scratch/DP/dfernand/Stamburri/PCGFS_PROJECT/ChIPseq/INPUT/mm10/input_{control}.bam"

# Parameters for the software used
params:
  bowtie: 
    global: "--chunkmbs 1024 -m 1 --best -S --no-unal -q"
    pe: "-I 10 -X 1000"
  fastp:
    se: "--stdin -t 1 -A -Q -L"
    pe: "-t 1 -A -Q -L"
  macs2:
    pk_calling: "--keep-dup all -m 3 30"
    gsize: mm
    pvalue: 1e-5
    pvalue_broad: 1e-5
    # -log10 pvalue for peak filtering -corresponds to the 8th column of the narrowPeak file. Default 10.
    filt_peaks_pval: "10"

# Determine the region corresponding to promoters around TSS
promoter:
  # After TSS
  aTSS: 2500
  # Before TSS
  bTSS: 2500

ref:
  # Bowtie index for the alignment of the sample
  index: /hpcnfs/techunits/bioinformatics/refdata/Mus_musculus/UCSC/mm10/Sequence/BowtieIndex/genome
  # Bowtie index for the alignmed of the spike-in, if there is
  index_spike: /hpcnfs/data/DP/dm6/dm6
  # File required by computeGCbias from deeptools
  2bit: /hpcnfs/data/DP/Databases/mm10.2bit
  # Used in computeGCbias to ignore repetitive regions in the calculation
  rep_masker: /hpcnfs/data/DP/Databases/RepeatMasker_noRandom_mm10.bed
  # File required by bdg2bigwig from ucsc
  chr_sizes: /hpcnfs/data/DP/Databases/mm10.chrom.sizes
  # https://deeptools.readthedocs.io/en/latest/content/feature/effectiveGenomeSize.html
  # 2304947926 --> mm9
  # 2308125349 --> mm10
  egenome_size: 2308125349

# Bam2bigwig params
bam2bigwig:
  read_extension: 200
  other: "--binSize 50"