
# Bowtie indexes
idx_bt1_mm9: /hpcnfs/techunits/bioinformatics/db/bowtie/mm9/mm9
idx_bt1_dm6: /hpcnfs/data/DP/dm6/dm6

# MACS2 parameters
macs2_g: mm
macs2_pvalue: 1e-5
macs2_pvalue_broad: 1e-5

# json files
SAMPLES_JSON: 'configFiles/samples.json'
CLUSTER_JSON: 'configFiles/cluster.json'

